// <auto-generated />
namespace Manager.Core.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mi_remove_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mi_remove_item));
        
        string IMigrationMetadata.Id
        {
            get { return "202108271220225_mi_remove_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
